name: CI

on:
  push:
  schedule:
  - cron: "0 2 * * 1-5"

jobs:
  ruby-tasks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch.
        uses: actions/checkout@v2.0.0
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'
      - run: sudo apt install libsqlite3-dev
      - run: gem install bigdecimal sequel sqlite3
      - run: ls -lart
      - run: ruby createdb.rb
      - name: Upload Apartment data
        uses: actions/upload-artifact@v1.0.0
        with:
          # Artifact name
          name: apartments.db
          # Directory containing files to upload
          path: apartments.db
