name: CI

on:
  push:
  schedule:
  - cron: "0 22,0-9 * * *"

jobs:
  update-database:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch.
        uses: actions/checkout@v2.0.0
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'
      - run: sudo apt install libsqlite3-dev
      - run: gem install bigdecimal sequel sqlite3
      - run: ls -lart
      - run: ruby update.rb
        env: 
          REVERSE: true
      - run: ruby getfirst.rb
      - name: Create an issue
        uses: DragonStuff/create-an-issue@v2.2.0
        with:
          assignees: DragonStuff
          filename: found_properties.txt
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
      - name: Upload Apartment data
        uses: actions/upload-artifact@v1.0.0
        with:
          name: apartments.db
          path: apartments.db
      - uses: DragonStuff/git-auto-commit-action@v2.5.0
        with:
          commit_message: Pushing new apartment db automatically.
          branch: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
