name: CI

on:
  push:
  schedule:
  - cron: "0 2 * * 1-5"

jobs:
  ruby-tasks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.x'
      - run: gem install bigdecimal sequel
      - run: ls -lart
      - run: ruby createdb.rb
